language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U setuptools furl orderedmultidict
# command to run tests, e.g. python setup.py test
script:  python lib/setup.py test
